{
  "openapi": "3.0.0",
  "x-generator": "Dynamic OpenAPI Generator v1.0.0",
  "info": {
    "title": "bunny.net API",
    "description": "<img src='https://bunny.net/v2/images/bunnynet-logo-dark.svg' style='width: 200px;' alt='bunny.net Logo'>\n               Learn how to use the [bunny.net](https://bunny.net \"bunny.net - The content delivery platform that truly hops.\") API. Everything that can be done with the control panel can also be achieved with our API documented on this page. To learn how to use the storage API, have a look at our <a href='https://bunnycdnstorage.docs.apiary.io/#'>storage API documenta[...]",
    "termsOfService": "https://bunny.net/tos",
    "contact": {
      "name": "bunny.net",
      "url": "https://docs.bunny.net",
      "email": "support@bunny.net"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.bunny.net",
      "description": "bunny.net API Server"
    }
  ],
  "paths": {
    "/country": {
      "get": {
        "tags": [
          "Countries"
        ],
        "summary": "Get Country List",
        "operationId": "CountriesPublic_GetCountryList",
        "security": [
          {
            "AccessKey": [
              "Subuser",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone": {
      "get": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "List DNS Zones",
        "operationId": "DnsZonePublic_Index",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Add DNS Zone",
        "operationId": "DnsZonePublic_Add",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{id}": {
      "get": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Get DNS Zone",
        "operationId": "DnsZonePublic_Index2",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Update DNS Zones",
        "operationId": "DnsZonePublic_Update",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Delete DNS Zone",
        "operationId": "DnsZonePublic_Delete",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{id}/export": {
      "get": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Export",
        "operationId": "DnsZonePublic_Export",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/checkavailability": {
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Check the DNS zone availability",
        "operationId": "DnsZonePublic_CheckAvailability",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{zoneId}/records/{id}": {
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Update DNS Record",
        "operationId": "DnsZonePublic_UpdateRecord",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Delete DNS Record",
        "operationId": "DnsZonePublic_DeleteRecord",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{zoneId}/import": {
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Import DNS Records",
        "operationId": "DnsZonePublic_Import",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{zoneId}/records": {
      "put": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Add DNS Record",
        "operationId": "DnsZonePublic_AddRecord",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "List Pull Zones",
        "operationId": "PullZonePublic_Index",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Pull Zone",
        "operationId": "PullZonePublic_Add",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Get Pull Zone",
        "operationId": "PullZonePublic_Index2",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Update Pull Zone",
        "operationId": "PullZonePublic_UpdatePullZone",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Delete Pull Zone",
        "operationId": "PullZonePublic_Delete",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/originshield/queuestatistics": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Get Origin Shield Queue Statistics",
        "operationId": "PullZonePublic_OriginShieldConcurrencyStatistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/safehop/statistics": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Get SafeHop Statistics",
        "operationId": "PullZonePublic_SafeHopStatistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/optimizer/statistics": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Get Optimizer Statistics",
        "operationId": "PullZonePublic_OptimizerStatistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/loadFreeCertificate": {
      "get": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Load Free Certificate",
        "operationId": "PullZonePublic_LoadFreeCertificate",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/edgerules/addOrUpdate": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add/Update Edge Rule",
        "operationId": "PullZonePublic_AddEdgeRule",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/edgerules/{edgeRuleId}/setEdgeRuleEnabled": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Set Edge Rule Enabled",
        "operationId": "PullZonePublic_SetEdgeRuleEnabled",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/purgeCache": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Purge Cache",
        "operationId": "PullZonePublic_PurgeCachePostByTag",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/checkavailability": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Check the pull zone availability",
        "operationId": "PullZonePublic_CheckAvailability",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/addCertificate": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Custom Certificate",
        "operationId": "PullZonePublic_AddCertificate",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/addHostname": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Custom Hostname",
        "operationId": "PullZonePublic_AddHostname",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/setForceSSL": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Set Force SSL",
        "operationId": "PullZonePublic_SetForceSSL",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/resetSecurityKey": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Reset Token Key",
        "operationId": "PullZonePublic_ResetSecurityKey",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/addAllowedReferrer": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Allowed Referer",
        "operationId": "PullZonePublic_AddAllowedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/removeAllowedReferrer": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Remove Allowed Referer",
        "operationId": "PullZonePublic_RemoveAllowedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/addBlockedReferrer": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Blocked Referer",
        "operationId": "PullZonePublic_AddBlockedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/removeBlockedReferrer": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Remove Blocked Referer",
        "operationId": "PullZonePublic_RemoveBlockedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/addBlockedIp": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Add Blocked IP",
        "operationId": "PullZonePublic_AddBlockedIp",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/removeBlockedIp": {
      "post": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Remove Blocked IP",
        "operationId": "PullZonePublic_RemoveBlockedIp",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{pullZoneId}/edgerules/{edgeRuleId}": {
      "delete": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Delete Edge Rule",
        "operationId": "PullZonePublic_DeleteEdgeRule",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/removeCertificate": {
      "delete": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Remove Certificate",
        "operationId": "PullZonePublic_RemoveCertificate",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/pullzone/{id}/removeHostname": {
      "delete": {
        "tags": [
          "Pull Zone"
        ],
        "summary": "Remove Custom Hostname",
        "operationId": "PullZonePublic_RemoveHostname",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary": {
      "get": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "List Video Libraries",
        "operationId": "VideoLibraryPublic_Index",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Add Video Library",
        "operationId": "VideoLibraryPublic_Add",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}": {
      "get": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Get Video Library",
        "operationId": "VideoLibraryPublic_Index2",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Update Video Library",
        "operationId": "VideoLibraryPublic_Update",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Delete Video Library",
        "operationId": "VideoLibraryPublic_Delete",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/languages": {
      "get": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Get Languages",
        "operationId": "VideoLibraryPublic_Index3",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/resetApiKey": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Reset Password",
        "operationId": "VideoLibraryPublic_ResetPassword",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/resetApiKey": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Reset Password",
        "operationId": "VideoLibraryPublic_ResetPassword2",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/addAllowedReferrer": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Add Allowed Referer",
        "operationId": "VideoLibraryPublic_AddAllowedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/removeAllowedReferrer": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Remove Allowed Referer",
        "operationId": "VideoLibraryPublic_RemoveAllowedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/addBlockedReferrer": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Add Blocked Referer",
        "operationId": "VideoLibraryPublic_AddBlockedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/removeBlockedReferrer": {
      "post": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Remove Blocked Referer",
        "operationId": "VideoLibraryPublic_RemoveBlockedReferrer",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/watermark": {
      "put": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Add Watermark",
        "operationId": "VideoLibraryPublic_AddWatermark",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Delete Watermark",
        "operationId": "VideoLibraryPublic_DeleteWatermark",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone": {
      "get": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "List Storage Zones",
        "operationId": "StorageZonePublic_Index",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Add Storage Zone",
        "operationId": "StorageZonePublic_Add",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone/{id}": {
      "get": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Get Storage Zone",
        "operationId": "StorageZonePublic_Index2",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Update Storage Zone",
        "operationId": "StorageZonePublic_Update",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Delete Storage Zone",
        "operationId": "StorageZonePublic_Delete",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone/checkavailability": {
      "post": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Check the storage zone availability",
        "operationId": "StorageZonePublic_CheckAvailability",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone/{id}/resetPassword": {
      "post": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Reset Password",
        "operationId": "StorageZonePublic_ResetPassword",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone/resetReadOnlyPassword": {
      "post": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Reset Read-Only Password",
        "operationId": "StorageZonePublic_ResetReadOnlyPassword",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStorage",
              "SubuserManage",
              "SubuserStorage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/region": {
      "get": {
        "tags": [
          "Region"
        ],
        "summary": "Region list",
        "operationId": "RegionPublic_Index",
        "security": [
          {
            "AccessKey": [
              "Subuser",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/purge": {
      "post": {
        "tags": [
          "Purge"
        ],
        "summary": "Purge URL",
        "operationId": "PurgePublic_IndexPost",
        "security": [
          {
            "AccessKey": [
              "InternalApi",
              "SubuserAPIManage",
              "SubuserAPIPullZones",
              "SubuserManage",
              "SubuserPullZones",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/transcribing/statistics": {
      "get": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Get Video Library Transcribing Statistics",
        "operationId": "GetTranscribingStatistics_Statistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/videolibrary/{id}/drm/statistics": {
      "get": {
        "tags": [
          "Stream Video Library"
        ],
        "summary": "Get Video Library DRM Statistics",
        "operationId": "GetDrmStatisticsEndpoint_Statistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStream",
              "SubuserManage",
              "SubuserStream",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/storagezone/{id}/statistics": {
      "get": {
        "tags": [
          "Storage Zone"
        ],
        "summary": "Get Storage Zone Statistics",
        "operationId": "StorageZonePublic_StorageZoneStatistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStatistics",
              "SubuserManage",
              "SubuserStatistics",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{id}/statistics": {
      "get": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Get DNS Query Statistics",
        "operationId": "DnsZonePublic_Statistics",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/dnszone/{id}/dnssec": {
      "post": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Enable DNSSEC on a DNS Zone",
        "operationId": "ManageDnsZoneDnsSecEndpoint_EnableDnsSecDnsZone",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "DNS Zone"
        ],
        "summary": "Disable DNSSEC on a DNS Zone",
        "operationId": "ManageDnsZoneDnsSecEndpoint_DisableDnsSecDnsZone",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIDns",
              "SubuserAPIManage",
              "SubuserDns",
              "SubuserManage",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/user/closeaccount": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "CloseAccount",
        "operationId": "CloseAccount_CloseAccount",
        "security": [
          {
            "AccessKey": [
              "Subuser",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/user/audit/{date}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "GetUserAuditLog",
        "operationId": "GetUserAuditLog_GetUserAuditLog",
        "security": [
          {
            "AccessKey": [
              "Subuser",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/statistics": {
      "get": {
        "tags": [
          "Statistics"
        ],
        "summary": "Get Statistics",
        "operationId": "StatisticsPublic_Index",
        "security": [
          {
            "AccessKey": [
              "SubuserAPIManage",
              "SubuserAPIStatistics",
              "SubuserManage",
              "SubuserStatistics",
              "User",
              "UserApi"
            ]
          }
        ]
      }
    },
    "/apikey": {
      "get": {
        "tags": [
          "API Keys"
        ],
        "summary": "List API Keys",
        "operationId": "ApiKeyPublic_ListApiKeys",
        "security": [
          {
            "AccessKey": [
              "User",
              "UserApi"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AccessKey": {
        "type": "apiKey",
        "description": "API Access Key authorization header",
        "name": "AccessKey",
        "in": "header"
      }
    }
  }
}
